@SoftwareCenter.Api_HostAddress = http://localhost:1337


# Add A Vendor to the API

POST {{SoftwareCenter.Api_HostAddress}}/commercial-vendors
Content-Type: application/json 

{
    "name": "Jetbrains",
    "site": "https://jetbrains.com",
    "contactFirstName": "John",
    "contactLastName": "Wick",
    "contactEmail": "jwick@revenge.com",
    "contactPhone": "888 123-456"
}

